# Generated by Django 2.1 on 2019-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190517_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='host',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='网站'),
        ),
    ]
